### Numpy

In [1]:
!pip install numpy


[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [9]:
# membuat array dari list

arr1 = np.array([1,2,3,4,5,6])
print("Array dari list :", arr1)

# membuat sebuah array dengan rentang nilai (start,stop,step)

arr2 = np.arange(0,10)
print("Array dari rentang nilai :",arr2)

# membuat array 2 dimensi yang berisi 0
arr3 = np.zeros((3,3))
print("Array dari zeros : \n",arr3)

# membuat array 2 dimensi yang berisi 1
arr4 = np.ones((3,3))
print("Array dari ones : \n",arr4)

Array dari list : [1 2 3 4 5 6]
Array dari rentang nilai : [0 1 2 3 4 5 6 7 8 9]
Array dari zeros : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array dari ones : 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
# membuat array linespace

arr5 = np.linspace(1,8,5)
print("Array dari linespace: ",arr5)

Array dari linespace:  [1.   2.75 4.5  6.25 8.  ]


In [12]:
# array manipulation

# array reshape

arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
# flatten array

flatt_arr = arr.flatten()
flatt_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
# transpose array

arr = np.arange(8).reshape(2,4)
arr

print("Array awal : \n", arr)

transposed_arr = arr.transpose()
print("Transpose array : \n", transposed_arr)

Array awal : 
 [[0 1 2 3]
 [4 5 6 7]]
Transpose array : 
 [[0 4]
 [1 5]
 [2 6]
 [3 7]]


In [16]:
# concantenate

arr6 = np.array([[1,2], [3,4]])
arr7 = np.array([[5,6]])

concant_arr = np.concatenate((arr6, arr7), axis=0)
print(concant_arr)

[[1 2]
 [3 4]
 [5 6]]


In [19]:
# numpy indexing

data_umur = np.array([22,21,20,18,25,23,24])

#akses element dengan array tertentu
index_tertentu = [1,3,5]
idx = data_umur[index_tertentu]
print(idx)

# ambil data elemen 1-3
data_umur[0:3]

# filter untuk umur kurang lebih di bawah 20
data_filter = data_umur[data_umur <=20]
data_filter



[21 18 23]


array([20, 18])

In [ ]:
# matematical operations di numpy

arr8 = np.array([1,2,3,4,5,6])
arr9 = np.arange(0,100).reshape(20,5)

# operasi matematika (penjumlahan)
jumlah = np.sum(arr8)
print(jumlah)

jumlah = np.sum(arr9)
print(jumlah)
arr9

21
4950


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [24]:
# operasi matematika (perkalian dot)

arr10 = np.array([1,2,3])
arr11 = np.array([4,5,6])

dot_product = np.dot(arr10, arr11)
print(dot_product)

32


In [28]:
# data penjualan

data_penjualan = np.arange(100000, 200000, 2000)
data_penjualan


array([100000, 102000, 104000, 106000, 108000, 110000, 112000, 114000,
       116000, 118000, 120000, 122000, 124000, 126000, 128000, 130000,
       132000, 134000, 136000, 138000, 140000, 142000, 144000, 146000,
       148000, 150000, 152000, 154000, 156000, 158000, 160000, 162000,
       164000, 166000, 168000, 170000, 172000, 174000, 176000, 178000,
       180000, 182000, 184000, 186000, 188000, 190000, 192000, 194000,
       196000, 198000])

In [29]:
# fungsi mean, median, sum di numpy
rata = data_penjualan.mean()
jumlah = data_penjualan.sum()
median = data_penjualan.std()

print(rata)
print(jumlah)
print(median)

149000.0
7450000
28861.739379323622


In [30]:
# broadcasting 

arr12 = np.array([[1,2,3], [4,5,6]])
scalar = 2

hasil = arr12 + scalar
print(hasil)

[[3 4 5]
 [6 7 8]]


In [33]:
# random sampling
# membuat array 2x3 dengan nilai acak dari distribusi uniform

random_arr = np.random.rand(2,3)
print("Array acak uniform : \n ", random_arr)

# membuat array dengan 5 bilangan acak antara 0-10

int_arr = np.random.randint(0,10,5)
print("Array bilangan bulat acak : \n ", int_arr)

Array acak uniform : 
  [[0.05967654 0.48123203 0.28826648]
 [0.3169534  0.46701718 0.95843502]]
Array bilangan bulat acak : 
  [0 6 0 6 5]


### Pandas

In [34]:
!pip install pandas


[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [35]:
import pandas as pd
import numpy as np

In [36]:
# contoh series

data_series = pd.Series([10,20,30,40,50])
print (data_series)

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [37]:
# dataFrame

data = {
    "Nama": ["Devi", "Ario", "Dany"],
    "Usia": [21,22,23],
    "Gaji": [1000,800,500]
}

df = pd.DataFrame(data=data)
df

Nama  Usia  Gaji
0  Devi    21  1000
1  Ario    22   800
2  Dany    23   500

In [ ]:
label = ['a', 'b', 'c']
data = [20,30,40]
series_label = pd.Series(data=data, index=label)
series_label

a    20
b    30
c    40
dtype: int64

In [40]:
list = [[1,2], [3,4], [5,6]]
kolom = ["kolom 1", "kolom 2"]
df_list = pd.DataFrame(data=list, columns=kolom)
df_list

kolom 1  kolom 2
0        1        2
1        3        4
2        5        6

In [41]:
# tambah kolom di dataframe

# dataFrame
data = {
    "Nama": ["Devi", "Ario", "Dany"],
    "Usia": [21,22,23],
}

df = pd.DataFrame(data=data)
df

df["Gaji"] = [1000,800,500]
df

Nama  Usia  Gaji
0  Devi    21  1000
1  Ario    22   800
2  Dany    23   500

In [43]:
# simpan data ke csv

df.to_csv('data_gaji.csv', columns=None)

In [46]:
df = pd.read_csv("./data_gaji.csv")
df

Unnamed: 0  Nama  Usia  Gaji
0           0  Devi    21  1000
1           1  Ario    22   800
2           2  Dany    23   500

In [ ]:
# Eksplorasi data

print(df.head())

   Unnamed: 0  Nama  Usia  Gaji
0           0  Devi    21  1000
1           1  Ario    22   800
2           2  Dany    23   500


In [48]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  3 non-null      int64 
 1   Nama        3 non-null      object
 2   Usia        3 non-null      int64 
 3   Gaji        3 non-null      int64 
dtypes: int64(3), object(1)
memory usage: 228.0+ bytes
None


In [49]:
print(df.describe())

       Unnamed: 0  Usia         Gaji
count         3.0   3.0     3.000000
mean          1.0  22.0   766.666667
std           1.0   1.0   251.661148
min           0.0  21.0   500.000000
25%           0.5  21.5   650.000000
50%           1.0  22.0   800.000000
75%           1.5  22.5   900.000000
max           2.0  23.0  1000.000000


In [50]:
df[df["Usia"] > 21]

Unnamed: 0  Nama  Usia  Gaji
1           1  Ario    22   800
2           2  Dany    23   500

In [51]:
df.iloc[1]

Unnamed: 0       1
Nama          Ario
Usia            22
Gaji           800
Name: 1, dtype: object

In [ ]:
# nambah data baru

df['Random'] = [23,45,np.nan]
df

Unnamed: 0  Nama  Usia  Gaji  Random
0           0  Devi    21  1000    23.0
1           1  Ario    22   800    45.0
2           2  Dany    23   500     NaN

In [54]:
# menghapus data
a = df.drop(columns=['Random'])
a

Unnamed: 0  Nama  Usia  Gaji
0           0  Devi    21  1000
1           1  Ario    22   800
2           2  Dany    23   500

In [55]:
# handling missing value
a.isnull().sum()

Unnamed: 0    0
Nama          0
Usia          0
Gaji          0
dtype: int64

In [58]:
# mendeteksi missing data

df_missing = pd.DataFrame(
    {
        "A" : [1,None,3],
        "B" : [4,5,None]
    }
)

df_missing.isnull().sum()
df_missing.fillna(df_missing.mean())

A    B
0  1.0  4.0
1  2.0  5.0
2  3.0  4.5

In [59]:
df_missing.duplicated()

0    False
1    False
2    False
dtype: bool

In [61]:
drop_data = df.drop(columns=["Gaji"])
drop_data

Unnamed: 0  Nama  Usia  Random
0           0  Devi    21    23.0
1           1  Ario    22    45.0
2           2  Dany    23     NaN